-- Write a SQL Query to find the TOP 3 Salary in each department.

CREATE OR REPLACE TABLE DEPARTMENT  
(
	ID INT ,
    NAME VARCHAR ,
    PRIMARY KEY (ID)
);
CREATE OR REPLACE TABLE EMPLOYEE  
(
	ID INT,
    NAME VARCHAR(20),
    SALARY INT,
    DEPARTMENTID INT ,
    PRIMARY KEY (ID) ,
    FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(ID)
);

INSERT INTO DEPARTMENT VALUES 
(1,'IT'),
(2,'SALES');

INSERT INTO EMPLOYEE VALUES 
(1,'Joe',85000,1),
(2,'Henry',80000,2),
(3,'Sam',60000,2),
(4,'Max',90000,1),
(5,'Janet',69000,1),
(6,'Randy',85000,1),
(7,'Will',70000,1);

SELECT D_NAME , E_NAME , SALARY FROM (
SELECT D.NAME AS D_NAME,E.NAME AS E_NAME ,SALARY 
,dense_rank() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RNK 
FROM EMPLOYEE E 
JOIN DEPARTMENT D 
ON E.DEPARTMENTID = D.ID
) WHERE RNK <= 3
;
