
CREATE OR REPLACE TABLE TESTS (
    PICKUP VARCHAR(10)
    ,DEST VARCHAR(10)
    ,COST NUMBER(5,0)
);

 

INSERT INTO TESTS (PICKUP, DEST, COST)
VALUES 
('A', 'B', 3),
('A', 'C', 2),
('A', 'D', 5),
('B', 'D', 4),
('B', 'F', 10),
('F', 'A', 6),
('F', 'E', 2),
('D', 'E', 1),
('A', 'E', 100)
;

SELECT * FROM TESTS;

SELECT TOP 1 STARTING_POINT,TRANSIT , FINAL , TOTAL_DIST FROM(
SELECT A.PICKUP AS STARTING_POINT,A.DEST AS TRANSIT,B.PICKUP,B.DEST AS FINAL, (A.COST+B.COST) AS TOTAL_DIST
FROM TESTS A 
JOIN TESTS B 
WHERE A.DEST = B.PICKUP AND B.DEST = 'E'
ORDER BY TOTAL_DIST ASC )
;