WITH CTE AS (
SELECT PRODUCT_ID ,SUM(SALES) as product_sales
FROM ORDERS 
GROUP BY PRODUCT_ID
ORDER BY PRODUCT_SALES DESC 
),
CALCULATE_SALES AS (
SELECT PRODUCT_ID , PRODUCT_SALES,
SUM(PRODUCT_SALES) OVER(ORDER BY PRODUCT_SALES DESC) AS RUNNING_SALES,
SUM(PRODUCT_SALES) OVER() AS TOTAL_SALES
FROM CTE
)
SELECT * FROM CALCULATE_SALES
WHERE RUNNING_SALES <= TOTAL_SALES *0.8
;
