-- WRITE AN SQL QUERY TO FIND THE START AND END DATE FOR EACH SUCESSION OF EVENTS  
USE DATABASE SQL;
create table tasks (
date_value date,
state varchar(10)
);
insert into tasks values 
('2019-01-01','success'),
('2019-01-02','success'),
('2019-01-03','success'),
('2019-01-04','fail'),
('2019-01-05','fail'),
('2019-01-06','success');

SELECT * FROM TASKS;

WITH DATE_CTE AS (
SELECT DATE_VALUE , STATE , 
row_number() OVER(PARTITION BY STATE ORDER BY DATE_VALUE ASC ) AS STATE_NEXT,
DATEADD(DAY ,-1*row_number() OVER(PARTITION BY STATE ORDER BY DATE_VALUE ASC ), DATE_VALUE )AS BASE_DATE 
FROM TASKS
ORDER BY DATE_VALUE
)
SELECT MIN(DATE_VALUE) AS START_DATE , 
MAX(DATE_VALUE) AS END_DATE , STATE
FROM DATE_CTE
GROUP BY BASE_DATE, STATE 
;
 
